const fs = require('fs');
const buffer = fs.readFileSync('client/src/index.css');

let text = buffer.toString('utf8');
text = text.replace(/\0/g, ''); // Remove all null bytes generated by UTF-16
fs.writeFileSync('client/src/index.css', text, 'utf8');
console.log("Fixed CSS encoding!");
