import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import StoreLayout from "@/components/StoreLayout";
import { useCart } from "@/contexts/CartContext";
import { formatCatalogPrice } from "@/lib/catalog";
import { resolveRetailerAction } from "@/lib/catalogInteractions";
import { toast } from "sonner";

function displayTotal(total: number) { return total ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(total) : "—"; }

export default function Cart() {
  const { items, count, total, updateQuantity, removeProduct, clearCart } = useCart(); const checkRetailer = (url?: string) => { const action = resolveRetailerAction(url); if (action.kind === "missing") return toast.message("This product needs its approved retailer destination before you can continue."); window.open(action.url, "_blank", "noopener,noreferrer"); };
  return <StoreLayout><main className="route-main cart-main"><section className="route-hero cart-hero"><p className="route-kicker">THE COZY CART / CART</p><h1>Your product<br /><em>shortlist.</em></h1><p>Add products while you shop, adjust quantities, then open a verified retailer destination for each product. The Cozy Cart does not process payments or checkout.</p></section>{!items.length ? <section className="empty-cart"><ShoppingBag size={30} /><h2>Your cart is empty.</h2><p>Browse the live catalog and add products you want to revisit.</p><a href="/shop">Shop products <ArrowRight size={16} /></a></section> : <section className="cart-layout"><div className="cart-items"><div className="cart-heading"><span>{count} item{count === 1 ? "" : "s"}</span><button onClick={clearCart}>Clear cart</button></div>{items.map((item) => <article className="cart-row" key={item.id}><div className="cart-art">{item.imageUrl ? <img src={item.imageUrl} style={{ objectPosition: item.imagePosition }} alt="" /> : <ShoppingBag size={22} />}</div><div><span>{item.category}</span><h2>{item.title}</h2><p>{formatCatalogPrice(item)}</p></div><div className="quantity-control"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={14} /></button><b>{item.quantity}</b><button onClick={() => updateQuantity(item.id, item.quantity + 1)} aria-label="Increase quantity"><Plus size={14} /></button></div><div className="cart-actions"><button onClick={() => checkRetailer(item.affiliateUrl)}>Retailer <ArrowRight size={14} /></button><button aria-label="Remove item" onClick={() => removeProduct(item.id)}><Trash2 size={16} /></button></div></article>)}</div><aside className="cart-summary"><p className="route-kicker">CART SUMMARY</p><div><span>Products</span><strong>{count}</strong></div><div><span>Known-price subtotal</span><strong>{displayTotal(total)}</strong></div><p>Subtotal only includes products that have a current known price. Retailer availability and final price are confirmed after handoff.</p><button onClick={() => checkRetailer(items.find((item) => item.affiliateUrl)?.affiliateUrl)}>Open first retailer <ArrowRight size={16} /></button></aside></section>}</main></StoreLayout>;
}
